[parity]
chain = "spec.json"
base_path = "./data"
keys_path = "../account/"
[network]
port = 30300
id = 34661
# reserved_peers = "peers.txt"
# min_peers = 1
# max_peers = 1
discovery = false
# allow_ips = "private"
[rpc]
port = 8540
interface = "all"
cors = ["all"]
apis = ["all"]
[websockets]
port = 8550
# interface = "127.0.0.1"
apis = ["all"]
max_connections = 99999
[account]
unlock = ["0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"]
password = ["../poa.pwds"]
[mining]
engine_signer = "0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"
reseal_on_txs = "none"
usd_per_tx = "0"
[misc]
log_file = "./data/parity.log"
