[parity]
chain = "demo.json"
base_path = "/mnt/ParityExt/data/"
[network]
port = 30301
[rpc]
port = 8541
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8551
[account]
unlock = ["0xfb1719eb4f531a51fea2502f300ebd23f4d80f6f"]
password = ["node.pwds"]
[mining]
engine_signer = "0x2cce318e140cbf544619e0df1dc2ae3bf33e8a7d"
reseal_on_txs = "none"
