[parity]
chain = "spec.json"
base_path = "/mnt/GethExt/data"
[network]
port = 30300
id = 34661
reserved_peers = "peers.txt"
min_peers = 3
max_peers = 3
discovery = false
# allow_ips = "private"
[rpc]
port = 8540
interface = "all"
# cors = ["all"]
apis = ["all"]
[websockets]
port = 8550
interface = "all"
apis = ["all"]
max_connections = 999999
[account]
unlock = ["0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"]
password = ["poa.pwds"]
[mining]
engine_signer = "0x5cc96b92aa5dd0ec7703cc5795e8aea766c667d2"
reseal_on_txs = "none"
usd_per_tx = "0"
[misc]
log_file = "/mnt/GethExt/log/parity.log"