[parity]
chain = "spec.json"
base_path = "/mnt/GethExt/data"
[network]
port = 30300
reserved_peers = "peers.txt"
min_peers = 10
max_peers = 10
discovery = false
[rpc]
port = 8540
interface = "all"
apis = ["all"]
[websockets]
port = 8450