[parity]
chain = "spec.json"
base_path = "/mnt/GethExt/data"
keys_path = "./account/"
[network]
port = 30300
id = 34661
reserved_peers = "peers.txt"
min_peers = 3
max_peers = 3
discovery = false
# allow_ips = "private"
[rpc]
port = 8540
interface = "all"
cors = ["all"]
apis = ["all"]
[websockets]
port = 8550
interface = "all"
apis = ["all"]
max_connections = 9999
[account]
unlock = ["0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"]
password = ["poa.pwds"]
[mining]
engine_signer = "0x6a9a8309a6c0d8751f438d947c2ad93a055126cf"
reseal_on_txs = "none"
usd_per_tx = "0"
[misc]
log_file = "/mnt/GethExt/log/parity.log"