[parity]
chain = "demo.json"
base_path = "/mnt/GethExt/data"
[network]
port = 30303
reserved_peers = "peers.txt"
min_peers = 10
max_peers = 10
[rpc]
port = 8543
interface = "all"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8553
[account]
unlock = ["0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"]
password = ["node.pwds"]
[mining]
engine_signer = "0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"
reseal_on_txs = "none"
usd_per_tx = "0"
