[parity]
chain = "spec.json"
base_path = "/mnt/GethExt/data"
[network]
port = 30300
reserved_peers = "peers.txt"
min_peers = 10
max_peers = 10
discovery = false
[rpc]
port = 8540
interface = "all"
apis = ["all"]
[websockets]
port = 8550
interface = "all"
apis = ["all"]
[account]
unlock = ["0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"]
password = ["node.pwds"]
[mining]
engine_signer = "0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"
reseal_on_txs = "none"
usd_per_tx = "0"
[misc]
log_file = "/mnt/GethExt/log/parity2.log"