[parity]
chain = "demo.json"
base_path = "/mnt/GethExt/data/"
[network]
port = 30303
[rpc]
port = 8543
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8553
[account]
unlock = ["0xfb1719eb4f531a51fea2502f300ebd23f4d80f6f"]
password = ["node.pwds"]
[mining]
engine_signer = "0x744da66f21b4b099918bedf8dc8b8c23543d135d"
reseal_on_txs = "none"
