[parity]
chain = "spec.json"
base_path = "/mnt//data"
keys_path = "./account/node0/"
[network]
port = 30300
id = 34661
reserved_peers = "peers.txt"
min_peers = 3
max_peers = 3
discovery = false
allow_ips = "private"
[rpc]
port = 8540
interface = "all"
cors = ["all"]
apis = ["all"]
[websockets]
port = 8550
interface = "all"
apis = ["all"]
max_connections = 999999
[account]
unlock = ["0x8b8d89a8d65031f56f2802386cb9dc1db66d2333"]
password = ["poa.pwds"]
[mining]
force_sealing = false
engine_signer = "0x4c0887c98165d62f12db9f9cc8c96c141e697a7c"
reseal_on_txs = "none"
usd_per_tx = "0"
tx_queue_size = 16384
tx_queue_mem_limit = 1024
[footprint]
cache_size_db = 256
cache_size_blocks = 256
cache_size_queue = 256
cache_size_state = 256
[misc]
log_file = "/mnt//log/parity.log"
